sudo: required
dist: trusty
branches:
  only:
  - master
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script:
- make -C monografia main.pdf
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: monografia/
  on:
    branch: master
